akun/urls.py
from django.urls import path
app_name = 'akun'
from .views import (
    registerPage, 
    loginPage, 
    logoutUser, 
    set_apd,
    detail_apd,
    list_apd
)

urlpatterns = [
    path('apd/', set_apd, name="apd"),
    path('daftar_rs/', list_apd, name="daftar_rs"),
    path('<int:id>/', detail_apd, name="detail-apd"),
    path('register/', registerPage, name="register"),
	path('login/', loginPage, name="login"),  
	path('logout/', logoutUser, name="logout")
]

praktikum/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include
from akun.views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('akun/', include('akun.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

akun/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE)
    masker_medis    = models.IntegerField(blank=True, null=True)
    masker_n95      = models.IntegerField(blank=True, null=True)
    hazmat          = models.IntegerField(blank=True, null=True)
    apron           = models.IntegerField(blank=True, null=True)
    hand_sanitizer  = models.IntegerField(blank=True, null=True)
    sarung_tangan   = models.IntegerField(blank=True, null=True)
    face_shield     = models.IntegerField(blank=True, null=True)
    sepatu_boots    = models.IntegerField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("akun:detail-apd", kwargs={"id": self.id})

akun/forms.py
from django.contrib.auth.forms import UserCreationForm, forms
from django.contrib.auth.models import User
from .models import Profile

class CreateUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProfileForm(forms.ModelForm):
    class Meta:
        model   = Profile
        fields  = (
            'masker_medis', 
            'masker_n95', 
            'hazmat',
            'apron',
            'hand_sanitizer',
            'sarung_tangan',
            'face_shield',
            'sepatu_boots'
        )

akun/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms.models import model_to_dict
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver
from django.db.models.signals import post_save

from .forms import CreateUserForm, ProfileForm
from .models import Profile

# Create your views here.
def registerPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST, request.FILES)

			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('home')
			

		context = {
			'form': form
			}
		return render(request, 'akun/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('home')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'akun/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('home')

def home(request):
    return render(request, 'akun/index.html')

@login_required()
def set_apd(request):
	Profile.objects.get_or_create(user=request.user)
	profile = request.user.profile
	form = ProfileForm(instance=profile)

	if request.method == 'POST':
		form = ProfileForm(request.POST, request.FILES, instance=profile)
		if form.is_valid():
			form.save()

	context = {'form':form}
	return render(request, 'akun/input_data.html', context)


def list_apd(request):
	User = get_user_model()
	rs = User.objects.all()
	context = {
		'rs': rs
	}
	return render(request, 'akun/list-instansi.html', context)


def detail_apd(request, id):
    object = ProfileForm(data=model_to_dict(Profile.objects.get(id=id-1)))
    context = {
        'object': object
    }
    return render(request, 'akun/detail_apd.html', context)

templates/akun/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <title>Donasi Kesehatan</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/templatemo-digital-trend.css' %}">

</head>
<body>

<!-- MENU BAR -->
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo.png' %}" style="width: 80px; height: 80px; object-fit: contain; object-position: center center;">
            Donasi Kesehatan
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="#about" class="nav-link smoothScroll">Tentang Kami</a>
                </li>
                <li class="nav-item">
                    <a href="#project" class="nav-link smoothScroll">Donasi</a>
                </li>
                <li class="nav-item">
                    <a href="#ourMission" class="nav-link smoothScroll">Misi Kami</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'akun:apd' %}" class="nav-link smoothscroll">Input Data APD</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'akun:login' %}" class="nav-link contact">Login/Sign Up</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- HERO -->
<section class="hero hero-bg d-flex justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-md-10 col-12 d-flex flex-column justify-content-center align-items-center">
                <div class="hero-text">

                    <h1 class="text-white" data-aos="fade-up">Mari kita bantu <br><strong> Petugas Kesehatan</strong></h1>

                    <a href="{% url 'akun:daftar_rs' %}" class="custom-btn btn-bg btn mt-3" data-aos="fade-up" data-aos-delay="100">Ayo
                        Donasi!</a>

                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="hero-image" data-aos="fade-up" data-aos-delay="300">

                    <img src="{% static 'images/working-girl.png' %}" class="img-fluid" alt="working girl">
                </div>
            </div>

        </div>
    </div>
</section>


<!-- ABOUT -->
<section class="about section-padding pb-0" id="about">
    <div class="container">
        <div class="row">

            <div class="col-lg-7 mx-auto col-md-10 col-12">
                <div class="about-info">

                    <h2 class="mb-4" data-aos="fade-up">Apa itu <strong>Donasi Kesehatan</strong> ?</h2>

                    <p class="mb-0" data-aos="fade-up">Donasi Kesehatan adalah salah satu bentuk cara membantu satu sama lain</p>
                </div>

                <div class="about-image" data-aos="fade-up" data-aos-delay="200">

                    <img src="{% static 'images/office.png' %}" class="img-fluid" alt="office">
                </div>
            </div>

        </div>
    </div>
</section>


<!-- List -->
<section class="project section-padding" id="project">
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-12 col-12">

                <h2 class="mb-5 text-center" data-aos="fade-up">
                    <strong>List Instansi Kesehatan</strong>
                </h2>

                <div class="owl-carousel owl-theme" id="project-slide">
                    <div class="item project-wrapper" data-aos="fade-up" data-aos-delay="100">
                        <img src="{% static 'images/List Rumah sakit/Rumah sakit JIH.jpg' %}" class="img-fluid" alt="project image">

                        <div class="project-info">
                            <small>Rumah Sakit JIH</small>

                            <h3>
                                <a href="project-detail.html">
                                    <span>Membutuhkan Masker</span>
                                    <a href="project-detail.html" class="project-icon btn-bg btn">Donate</a>
                                </a>
                            </h3>
                        </div>
                    </div>

                    <div class="item project-wrapper" data-aos="fade-up">
                        <img src="images/List Rumah sakit/Rumah sakit Jogja.png" class="img-fluid" alt="project image">

                        <div class="project-info">
                            <small>Rumah Sakit Jogja</small>

                            <h3>
                                <a href="project-detail.html">
                                    <span>Membutuhkan Sarung Tangan</span>
                                    <a href="project-detail.html" class="project-icon btn-bg btn">Donate</a>
                                </a>
                            </h3>
                        </div>
                    </div>

                    <div class="item project-wrapper" data-aos="fade-up">
                        <img src="images/List Rumah sakit/Rumah sakit sardjito.jpg" class="img-fluid" alt="project image"style="width: %">

                        <div class="project-info">
                            <small>Rumah Sakit Sardjito</small>

                            <h3>
                                <a href="project-detail.html">
                                    <span>Membutuhkan pelingung wajah</span>
                                    <a href="project-detail.html" class="project-icon btn-bg btn">Donate</a>
                                </a>
                            </h3>
                        </div>
                    </div>

                    <div class="item project-wrapper" data-aos="fade-up">
                        <img src="images/List Rumah sakit/Rumah sakit senopati.jpg" class="img-fluid" alt="project image">

                        <div class="project-info">
                            <small>Rumah Sakit Senopati</small>

                            <h3>
                                <a href="project-detail.html">
                                    <span>Membutuhkan perlnegkapan APD</span>
                                    <a href="project-detail.html" class="project-icon btn-bg btn">Donate</a>
                                </a>
                            </h3>
                        </div>
                    </div>

                    <div class="item project-wrapper" data-aos="fade-up">
                        <img src="images/List Rumah sakit/Rumah sakit Panti Rapih Yogya.jpg" class="img-fluid" alt="project image">

                        <div class="project-info">
                            <small>Rumah Sakit Panti Rapih Yogya</small>

                            <h3>
                                <a href="project-detail.html">
                                    <span>Membutuhkan masker</span>
                                    <a href="project-detail.html" class="project-icon btn-bg btn">Donate</a>
                                </a>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <center><a href="{% url 'akun:daftar_rs' %}" class="read-more-btn btn-bg btn mt-3">Lihat Semua</a></center>
</section>


<!-- TESTIMONIAL -->
<section class="testimonial section-padding" id="ourMission">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-md-5 col-12">
                <div class="contact-image" data-aos="fade-up">

                    <img src="{% static 'images/female-avatar.png' %}" class="img-fluid" alt="website">
                </div>
            </div>

            <div class="col-lg-6 col-md-7 col-12">
                <h4 class="my-5 pt-3" data-aos="fade-up" data-aos-delay="100">Misi Kami</h4>

                <div class="quote" data-aos="fade-up" data-aos-delay="200"></div>

                <h2 class="mb-4" data-aos="fade-up" data-aos-delay="300">Manusia adalah makhluk sosial yang dimana saling membutuhkan satu sama lain, dengan ada nya ini merupakan salah satu cara untuk membantu sesama kita.</h2>

                <p data-aos="fade-up" data-aos-delay="400">
                    <strong>DoKes</strong>

                

                    <small>(Donasi Kesehatan)</small>
                </p>
            </div>

        </div>
    </div>
</section>


<footer class="site-footer">
    <div class="container">
        <div class="row">

            <div class="col-lg-5 mx-lg-auto col-md-8 col-10">
                <h1 class="text-white" data-aos="fade-up" data-aos-delay="100">We saves <strong> peoples </strong> lifes.</h1>
            </div>

            <div class="col-lg-3 col-md-6 col-12" data-aos="fade-up" data-aos-delay="200">
                <h4 class="my-4">Contact Info</h4>

                <p class="mb-1">
                    <i class="fa fa-phone mr-2 footer-icon"></i>
                    +6221 111 222
                </p>

                <p>
                    <a href="#">
                        <i class="fa fa-envelope mr-2 footer-icon"></i>
                        hello@dokes.com
                    </a>
                </p>
            </div>

            <div class="col-lg-3 col-md-6 col-12" data-aos="fade-up" data-aos-delay="300">
                <h4 class="my-4">Our Address</h4>

                <p class="mb-1">
                    <i class="fa fa-home mr-2 footer-icon"></i>
                    Jl. Magelang KM 9, Jl. Gito Gati No.18, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55511
                </p>
            </div>

            <div class="col-lg-4 mx-lg-auto text-center col-md-8 col-12" data-aos="fade-up" data-aos-delay="400">
                <p class="copyright-text">Copyright &copy; 2020 Donasi Kesehatan</p>
            </div>

            <div class="col-lg-4 mx-lg-auto col-md-6 col-12" data-aos="fade-up" data-aos-delay="500">

                <ul class="footer-link">
                    <li><a href="#">Stories</a></li>
                    <li><a href="#">Work with us</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
            </div>

            <div class="col-lg-3 mx-lg-auto col-md-6 col-12" data-aos="fade-up" data-aos-delay="600">
                <ul class="social-icon">
                    <li><a href="#" class="fa fa-instagram"></a></li>
                    <li><a href="#" class="fa fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-dribbble"></a></li>
                    <li><a href="#" class="fa fa-behance"></a></li>
                </ul>
            </div>

        </div>
    </div>
</footer>


<!-- SCRIPTS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/akun/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <title>Donasi Kesehatan</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
               
    <!-- Login container style -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/templatemo-digital-trend.css' %}">

    <style>
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			position: relative;
			display: flex;
            background: #74cfbf;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>

<!-- MENU BAR -->
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logo.png' %}"
                 style="width: 80px; height: 80px; object-fit: contain; object-position: center center;">
            Donasi Kesehatan
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'home' %}#about" class="nav-link smoothScroll">Tentang Kami</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'home' %}#project" class="nav-link smoothScroll">Donasi</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'home' %}#ourMission" class="nav-link smoothScroll">Misi Kami</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'akun:apd' %}" class="nav-link smoothScroll">Input Data APD</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'akun:login' %}" class="nav-link contact">Login/Sign up</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- Login  -->
<section class="blog section-padding">
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


				<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'akun:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</section>

<footer class="site-footer">
    <div class="container">
        <div class="row">

            <div class="col-lg-5 mx-lg-auto col-md-8 col-10">
                <h1 class="text-white" data-aos="fade-up" data-aos-delay="100">We saves <strong> peoples </strong>
                    lifes.</h1>
            </div>

            <div class="col-lg-3 col-md-6 col-12" data-aos="fade-up" data-aos-delay="200">
                <h4 class="my-4">Contact Info</h4>

                <p class="mb-1">
                    <i class="fa fa-phone mr-2 footer-icon"></i>
                    +6221 111 222
                </p>

                <p>
                    <a href="#">
                        <i class="fa fa-envelope mr-2 footer-icon"></i>
                        hello@dokes.com
                    </a>
                </p>
            </div>

            <div class="col-lg-3 col-md-6 col-12" data-aos="fade-up" data-aos-delay="300">
                <h4 class="my-4">Our Address</h4>

                <p class="mb-1">
                    <i class="fa fa-home mr-2 footer-icon"></i>
                    Jl. Magelang KM 9, Jl. Gito Gati No.18, Tridadi, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa
                    Yogyakarta 55511
                </p>
            </div>

            <div class="col-lg-4 mx-lg-auto text-center col-md-8 col-12" data-aos="fade-up" data-aos-delay="400">
                <p class="copyright-text">Copyright &copy; 2020 Donasi Kesehatan</p>
            </div>

            <div class="col-lg-4 mx-lg-auto col-md-6 col-12" data-aos="fade-up" data-aos-delay="500">

                <ul class="footer-link">
                    <li><a href="#">Stories</a></li>
                    <li><a href="#">Work with us</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
            </div>

            <div class="col-lg-3 mx-lg-auto col-md-6 col-12" data-aos="fade-up" data-aos-delay="600">
                <ul class="social-icon">
                    <li><a href="#" class="fa fa-instagram"></a></li>
                    <li><a href="#" class="fa fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-dribbble"></a></li>
                    <li><a href="#" class="fa fa-behance"></a></li>
                </ul>
            </div>

        </div>
    </div>
</footer>


<!-- SCRIPTS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>